### ISSUE TITLE
Verify for Custom Data

### ISSUE THREAD

**Issue by bytesByHarsh** [yuanhui360/CPP-Programming-on-Linux#2]
Hi,

So according to [this line](https://github.com/yuanhui360/CPP-Programming-on-Linux/blob/main/YH-123/verify_x509.cpp#L27) `X509_verify` is done which is verifying only the signature.

And according to [this line](https://github.com/yuanhui360/CPP-Programming-on-Linux/blob/main/YH-123/x509_certificate.cpp#L257) `EVP_sha256` is used. This function is not taking any input to generate the hash.

What changes can I make so that I am able to add custom data for verifying the signature?

I am a little new to these topics, hope you can give me some clarity on them!

**Comment by yuanhui360** [comment]
Good Afternoon Harsh
x509_verify(() is verify certificate, x509 is kind of digital document, this verify is verifying if certificate has been changed or not.I have made a video discuss sign and verify, in short words, sign the document using private key, and verify document with signature using public key.In generate_x509() method do this is just make sure our certificate generated OK.

Sign document need private key and algorithm, EVP_sha256() is hash algorithm, in my example, I just pick up one that very popular used. you are able to use other algorithm for instance EVP_sha512(), etc.
Certificate customer data usually using subject name, issuer name, validity period ...For example, parse period not before and not after to verify if certificate has expired or not.One possible way is using CN (common name string setup custom data, and parse it for verifying.It's all depend on your security designWish my example, my video helps.


    On Thursday, August 18, 2022 at 05:50:55 a.m. EDT, Harsh Mittal ***@***.***> wrote:  
 
 


Hi,

So according to this line X509_verify is done which is verifying only the signature.

And according to this line EVP_sha256 is used. This function is not taking any input to generate the hash.

What changes can I make so that I am able to add custom data for verifying the signature?

I am a little new to these topics, hope you can give me some clarity on them!

**Comment by bytesByHarsh** [comment]
Hi,

Thanks for clearing that out and creating such awesome content!
